### PR TITLE
fn_datatable_utils-1.0.1

### PR DESCRIPTION
**Pull request by LiamMahoney**
## Description

Changing the 'Data Table Utils: Get Row' function to use `.get()` instead of bracket notation when accessing the values of a cell. 

## Motivation and Context

#59 

## How Has This Been Tested?

Verified that a `KeyError` is no longer thrown with the new code

## Checklist:

- [x] I have added a [Signed-off-by](https://github.com/IBMResilient/resilient-community-apps/blob/master/CONTRIBUTING.md)
- [x] Either no new documentation is required by this change, OR I added new documentation
- [x] Either no new tests are required by this change, OR I added new tests
- [x] I have run pep8 and pylint. I have cleaned up all valid errors and warnings in code I have added or modified. These tools may generate false positives. Don't be worried about ignoring some errors or warnings. The goal is clean, consistent, and readable code.

Signed-off-by: LiamMahoney <liammahoney96@gmail.com>

### CODE REVIEW

**Comment by LiamMahoney** [comment]
forgot to use `git commit -S -m '...'` on https://github.com/ibmresilient/resilient-community-apps/pull/60/commits/702c4ff1d45a7a73bc9a386f9167f957e55b043d

**Review by MarkScherfling — COMMENTED** [review]
this change will be incorporated into the next release by end of month. We push from another internal repo so we don't accept changes here directly.

**Comment by LiamMahoney** [comment]
Sweet, thanks Mark!

**Comment by annmarien** [comment]
I believe that this issue is fixed as the functions have been re-written in the 2.0.0 release.  There is more error checking and .get is used.  Thanks for submitting this fix Liam.

**Pull request closed without merging**
